version: '3'
services:
  app:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./build:/C:\INCUBATOR\portfolio\frontend\portfolio_src
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
